# Server
server.port=8080
spring.application.name=ClyvoPet

# Oracle DataSource
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=RM565760
spring.datasource.password=150606
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cache
spring.cache.type=simple

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.packages-to-scan=br.com.fiap.ClyvoPet
springdoc.swagger-ui.disable-swagger-default-url=true
spring.data.web.pageable.one-indexed-parameters=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
